# SPDX-License-Identifier: MIT
# Copyright (c) 2019 Gennady Trafimenkov
---

# https://docs.docker.com/install/linux/docker-ce/ubuntu/#set-up-the-repository

- name: Installing dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: true
    cache_valid_time: 3600
  become: yes

- name: Add Docker's official GPG key
  apt_key: url=https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg id=0EBFCD88 state=present
  become: yes

- name: Add Docker's stable repository
  apt_repository: repo="deb [arch={{ansible_architecture|replace('aarch64', 'arm64')|replace('x86_64', 'amd64')}}] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable" state=present update_cache=yes
  become: yes

- name: Create config folder
  file: path=/etc/docker state=directory
  become: yes

- name: Copy docker daemon.json
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json
  become: yes

- name: Install packages
  apt:
    name:
      - docker-ce
    update_cache: true
    cache_valid_time: 3600
  become: yes
