# SPDX-License-Identifier: MIT
# Copyright (c) 2020 Gennady Trafimenkov
---

- name: Add Oracle VirtualBox public key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    id: A2F683C52980AECF
    state: present
  become: yes

- name: Add Oracle VirtualBox repository
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/{{ansible_distribution|lower}} {{ansible_distribution_release}} contrib"
    state: present
    update_cache: yes
  become: yes

- name: Install VirtualBox package
  apt:
    name: "{{ virtualbox_package }}"
    update_cache: true
    cache_valid_time: 3600
  when: virtualbox_package != ''
  become: yes
